name: Build Citron Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du dépôt avec sous-modules
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Initialiser les sous-modules
        run: git submodule update --init --recursive

      - name: Installer les outils de build
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential git

      - name: Installer vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg
          ./bootstrap-vcpkg.sh
          cd ..

      - name: Installer les dépendances vcpkg
        run: ./vcpkg/vcpkg install --triplet x64-linux

      - name: Configuration du projet
        run: |
          mkdir -p build
          cd build
          cmake -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake ..

      - name: Compilation du projet
        run: |
          cd build
          cmake --build .

      - name: Exécution des tests
        run: |
          cd build
          ctest --output-on-failure
