name: Build Citron Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v3

      # Optionnel : installer les dépendances nécessaires si elles ne sont pas déjà présentes sur l'image
      - name: Installer les outils de build
        run: sudo apt-get update && sudo apt-get install -y cmake build-essential

      - name: Configuration du projet
        run: |
          mkdir -p build
          cd build
          cmake ..

      - name: Compilation du projet
        run: |
          cd build
          cmake --build .

      # Si vous avez défini des tests avec CTest, cette étape les exécutera
      - name: Exécution des tests
        run: |
          cd build
          ctest --output-on-failure
